### ISSUE TITLE
CGMES performance regression

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-core#1032]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**

On a french EHV+HV grid, import take 1m10s on my (fast) computer. Is is slow especially compare to previous performance benchmarks. I suspect recent regressions. A quick profiling shows surprising bottlenecks for instance in PropertyBag.tabultate, Logger.debug, SubstationIdMapping.grapSubstationTransformers.

![image](https://user-images.githubusercontent.com/632675/69638853-d03dc980-105b-11ea-9090-e87a1543f119.png)

Memory consumption is also huge more than 2Go. I also suspect a regression here:

![image](https://user-images.githubusercontent.com/632675/69639218-6e319400-105c-11ea-898b-600cdabc33f3.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Just import a large network.

* **What is the expected behavior?**
I think, initially import was around 20s.

* **What is the motivation / use case for changing the behavior?**
To improve performance.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by MioRtia** [comment]
Hi,
Out of curiosity, when you say it initially took 20ms, was it a long time ago or only last release? I am trying to guess when the regression took place... The bottlenecks you mention are surprising to me, I don’t recall vast modifications on them.

Regarding memory, @zamarrenolm do you think it may be the refactoring of regulating controls?

**Comment by geofjamg** [comment]
No it was a long time ago, probably with a very partial import, so probably it is not anymore a valid target.

**Comment by MioRtia** [comment]
Okay, it would explain big increases for Logger.debug and PropertyBag.tabulate (there are way more elements to import now). It would be interesting to look at performances in not-debug mode.

The memory consumption worries me though, it shouldn't be so high. Several maps are created for regulating controls (they can only be set at the end of the conversion) but if they are the causes, we will have to think about something else.

**Comment by geofjamg** [comment]
In non debug mode (you are right it is a more relevant benchmark):

![image](https://user-images.githubusercontent.com/632675/69649271-15b6c280-106d-11ea-8f98-59040971e692.png)

**Comment by geofjamg** [comment]
We can see that only SubstationIdMapping.grapSubstationTransformers seems to be suspect (1/4 of the execution time).

**Comment by zamarrenolm** [comment]
I suspect that SubstationIdMapping.graphSubstationTransformers seems guilty because it is the method that provokes the initial load of cache of terminals ... I will take a more detailed look at it.
