### ISSUE TITLE
Shunt compensator import mistake

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-core#1037]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Shunt compensators seem to be incorrectly imported. Taking RTE data, capacitors in Convergence become inductors in IIDM model when going through CVG -> CGMES -> IIDM compare to CVG -> IIDM conversion.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
Shunt compensator susceptance sign should be conserved.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Can we remove this issue ?

**Comment by geofjamg** [comment]
> Can we remove this issue ?

Yes

**Comment by annetill** [comment]
There is no bug in the CGMES conversion. The bug was located earlier in the workflow.
