### ISSUE TITLE
getConnectableBus throws AssertionError 

### ISSUE THREAD

**Issue by jeandemanged** [powsybl/powsybl-core#1051]
* **Do you want to request a *feature* or report a *bug*?**
A bug

* **What is the current behavior?**
For some Terminals, calling getConnectableBus() results in an AssertionError being thrown. Seems to happen for dead substations.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
See attached minimal IIDM file. Calling getConnectableBus() on the generator's Terminal reproduces the issue.

[small.zip](https://github.com/powsybl/powsybl-core/files/3921271/small.zip)

* **What is the expected behavior?**
No AssertionError being thrown, getConnectableBus() returns null (as it was the case in previous 2.6.0 release)

* **Please tell us about your environment:**
  - PowSyBl Version: 3.0.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
`
java.lang.AssertionError: Should not happen
        at com.powsybl.iidm.network.impl.NodeBreakerVoltageLevel$CalculatedBusTopology.getConnectableBus(NodeBreakerVoltageLevel.java:405)
        at com.powsybl.iidm.network.impl.NodeTerminal$3.getConnectableBus(NodeTerminal.java:72)
        at com.powsybl.iidm.network.impl.NodeTerminal$3.getConnectableBus(NodeTerminal.java:63)
`

**Comment by MioRtia** [comment]
Hi,

This issue should be resolved in next release, the commit to correct it has been merged:  https://github.com/powsybl/powsybl-core/commit/ffd607cdcad8ade3890b13c013a825647b61b1c8 (PR https://github.com/powsybl/powsybl-core/pull/988)
