### ISSUE TITLE
In CIM1 Importer section count could be greater than maximum sections

### ISSUE THREAD

**Issue by zamarrenolm** [powsybl/powsybl-core#117]
In some network samples we have observed that the state variable `SvShuntCompensator.continuousSections` is greater than the EQ attribute `ShuntCompensator.maximumSections`.

The IIDM shunt compensator adder throws an exception when finds this problem.

The proposal is to change the call to shunt compensator adder in `CIM1Converter::createShunt` by: 

	`.setMaximumSections(Math.max(sc.getMaximumSections(), sectionCount)`

**Comment by mathbagu** [comment]
We also have to add a warning in the ```CIM1Converter::createShunt``` method with the two different values like it's done for the ```bPerSection``` property.

**Comment by mathbagu** [comment]
Fixed in #232
