### ISSUE TITLE
test jars jpms module name

### ISSUE THREAD

**Issue by jonenst** [powsybl/powsybl-core#1173]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Test jars have the same automatic-module-name as main jars. For example powsybl-commons.jar and powsybl-commons-tests.jar.
this means we can't use test jars and main jar together as jpms modules.

* **What is the expected behavior?**
Different module names

* **What is the motivation / use case for changing the behavior?**
Improve java9 integration

**Comment by geofjamg** [comment]
There is only one test jar anymore (iidm tck) so this is issue seems not to be relevant
