### ISSUE TITLE
[MergingView] Manage empty UcteXnodeCode

### ISSUE THREAD

**Issue by tadam50** [powsybl/powsybl-core#1183]
* **Do you want to request a *feature* or report a *bug*?**
Refactoring

* **What is the current behavior?**
No specific management is done for DanglingLine with empty UcteXnodeCode

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Merge 2 networks with DanglingLine with empty UcteXnodeCode.
MergedLine will be created even if is incoherent (2 networks without common borders)

* **What is the expected behavior?**
No MergedLine must be created when UcteXnodeCode is empty.
Only automatic Mergedline will keep empty UcteXnodeCode.
The xnode code is not a mandatory information so you can just skip it. The idea we have is to use both Xnode and MergedXnode extensions and initialize the attributes from these extensions, so not directly when the object is created.
As the name of the XNode is not mandatory, we have to find another way to cache the merged lines

* **What is the motivation / use case for changing the behavior?**
Refactor

* **Please tell us about your environment:**
  - PowSyBl Version: 3.2.0-SNAPSHOT
  - OS Version: Window 10 / Java 8

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
Issue will be done into MergingView development

**Comment by annetill** [comment]
Solved by #2442
