### ISSUE TITLE
Migration IIDM extensions to new extension API

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-core#1206]
* **Do you want to request a *feature* or report a *bug*?**
Neither - Migration following an API change

* **What is the current behavior?**
`MergedXNode`, `CoordinatedReactiveControl`, `TwoWindingsTransformerPhaseAngleClock`, `ThreeWindingsTransformerPhaseAngleClock`, `CgmesModelExtension`, `CgmesConversionContextExtension` and `EntsoeArea` are still implemented using the deprecated extension API.

* **What is the expected behavior?**
These extensions should be implemented using the new extension API.

* **What is the motivation / use case for changing the behavior?**
Being able to create custom implementations of these extensions.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.3.0-SNAPSHOT

**Other information**
One PR can be done per migration (the priority order is the enunciation order above)

**Comment by yichen88** [comment]
@sylvlecl 
Can i do this PR?
