### ISSUE TITLE
Upgrade to Groovy 3

### ISSUE THREAD

**Issue by jonenst** [powsybl/powsybl-core#1211]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Using Groovy 2

* **What is the expected behavior?**
Groovy 3

* **What is the motivation / use case for changing the behavior?**
Groovy3 has support for parsing java8 code, which allows it's groovydoc tool to work on our code.
Also it's the latest stable version

**Comment by jonenst** [comment]
groovy 3.0.5 | Central | 3 | Jul, 2020

**Comment by geofjamg** [comment]
Done
