### ISSUE TITLE
Rename sensitivity computation into sensitivity analysis

### ISSUE THREAD

**Issue by agnesLeroy** [powsybl/powsybl-core#1225]
At the moment the term "sensitivity computation" is used throughout the sensitivity-api.
However, sensitivity analysis is more widely used in the community to refer to such calculations. Thus, it seems advisable to change the naming in Powsybl. 

Also, the artifact sensitivity-api could be renamed into sensitivity-analysis-api to match the naming of security-analysis-api.

**Comment by annetill** [comment]
Resolved but I don't have the number of the PR :-)

**Comment by mathbagu** [comment]
Done in #1474
