### ISSUE TITLE
Create convenient method hasRatioTapChanger() and hasPhaseTapChanger()

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-core#1227]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
To check if a `TwoWindingsTransformer` or a `ThreeWindingsTransformer.Leg` has a ratio tap changer or a phase tap changer, `getRatio/PhaseTapChanger() != null` must be checked.

* **What is the expected behavior?**
We would like a `boolean hasRatio/PhaseTapcher()` method for these network components

* **What is the motivation / use case for changing the behavior?**
Increase readability

* **Please tell us about your environment:**
  - PowSyBl Version: 3.3.0-SNAPSHOT
  - OS Version: *

**Comment by yichen88** [comment]
why not return an optional?
