### ISSUE TITLE
CGMES equivalent injections at boundary and regulating voltage

### ISSUE THREAD

**Issue by zamarrenolm** [powsybl/powsybl-core#1297]
* **Do you want to request a *feature* or report a *bug*?**
Feature.

* **What is the current behavior?**
Current version of CGMES conversion (3.3.0) does not consider voltage regulation on equivalent injections located at boundaries.

* **What is the expected behavior?**
Voltage regulation should be kept in IIDM, but only for equivalent injections that represent HVDC links. This means that IIDM should allow to model a regulated voltage at a boundary point. A proposal to achieve this:
  - Preserve a node/bus for the boundary point (current conversion drops all boundary points, they are not present in IIDM model).
  - Introduce a fictitious generator that is able to regulate voltage at the preserved boundary node/bus.

* **What is the motivation / use case for changing the behavior?**
According to current ENTSO-E vision for CGMES quality of datasets and recommendations for network modeling and exchanges, voltage regulation in equivalent injections is not recommended when these objects are used to represent boundary flows between IGMs, but they are allowed when they are used to represent HVDC flows at boundaries.

  A warning should be raised if equivalent injections regulating voltage are used to represent flows between IGMs.

  But if the equivalent injections represent HVDC flows at boundaries, they could be allowed to regulate voltage. According to current ENTSO-E proposals, these situations should be reported adding the text “HVDC” in the description of the Topological Node or Connectivity Node at boundary.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.3.0.

**Comment by annetill** [comment]
Resolved with #1357
