### ISSUE TITLE
CGMES export of NonLinearShuntCompensator 

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-core#1389]
* **Do you want to request a *feature* or report a *bug*?**

A feature.

* **What is the current behavior?**

Current export does not support ````NonLinearShuntCompensators````.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

That all sections (b,g) could be updated. Also the maximum section count if we want to support the adding of a new section.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by MioRtia** [comment]
Solved by #1322
