### ISSUE TITLE
Calculated times series creation with decimal number

### ISSUE THREAD

**Issue by marifunf** [powsybl/powsybl-core#1421]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
The calculated dsl loader does not allow to create constant time series with a decimal number.
ts['ts_name'] = 1 is OK
ts['ts_name'] = 1.5 is NOK (runtime error)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create a calcutated series ts['ts_name'] = decimal number

* **What is the expected behavior?**
The ts ts_name is created

* **What is the motivation / use case for changing the behavior?**
Sometimes the numerical value is a computed one and it is not easy to understand how to avoid the runtime error

* **Please tell us about your environment:**
  - PowSyBl Version: 3.3
  - OS Version: Fedora 29

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

java.lang.RuntimeException: java.util.concurrent.ExecutionException: groovy.lang.MissingPropertyException: No such property: ts_name for class: com.powsybl.timeseries.CalculatedTimeSeriesDslLoader

it seems that in case of decimal, the default type is BigDecimal (https://www.logicbig.com/tutorials/misc/groovy/numbers-types-suffix.html) and there is no function void putAt(String name, BigDecimal value) in CalculatedTimeSeriesDslLoader class

**Comment by mathbagu** [comment]
Fixed in #1422
