### ISSUE TITLE
[MergingView] Create a DanglingLine

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#1426]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
It seems that when a DanglingLine is created from the MergingView, we try to create the MergedLine twice: one time by the MergingView itself, and another time by the MergedLineListener that listen the creation events.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
It's not really a bug because it seems to be properly managed, but I think we should not try to create the MergedLine from the mergingview and rely on the events only.

* **What is the expected behavior?**
Try to create the MergedLine only once.

* **What is the motivation / use case for changing the behavior?**
Make the merging of DanglingLine logic simpler

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Solved by #2442
