### ISSUE TITLE
[MergingView] HVDC Creation

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#1427]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
It's not possible to create a HVDC line between two voltage levels from two different networks. We do not have a DanglingLine equivalent for HVDC component. Currently the HVDC line would be stored in the merging view it-self, but during the export we do not know what to do with the HVDC line.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create a HVDC line between two different networks throw an exception.

* **What is the expected behavior?**
Support all equipment types creation or do not support all equipment types creation, but be consistent.

* **What is the motivation / use case for changing the behavior?**
Consistency of the API.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Solved by #2442
