### ISSUE TITLE
[MergingView] Line creation

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#1428]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
It's possible to create a Line between voltage levels from two different networks, by creating two dangling lines and a MergedLine. But in the LineAdder, we cannot set the Xnode code. This issue is related to #1425: dangling line without any xnode code should not be merged together.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create two networks, merge them into a MergingView, and create a line between the two networks

* **What is the expected behavior?**
I think we should not support that feature and make it impossible to create equipments that are part of several networks.

* **What is the motivation / use case for changing the behavior?**
Consistency of the API.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Solved by #2442
