### ISSUE TITLE
[MergingView] MergedLine flow computation is probably wrong

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#1429]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Currently, we consider that the MergedLine is a classic line, but it could be modeled as two lines in series. In that case, the B1/G1 should be split and stored in two b/g attributes in the DanglingLine. To do that we have to modify the model of the DanglingLine. The MergedLine would look like to a TieLine.

Depending on the modelling we choose, we have to fix the computation of P0 and Q0 that are assigned to the DanglingLine.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
No idea: this issue is related to the thinking about the modelling of the borders. 

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Solved by #2442
