### ISSUE TITLE
[MergingView] XNode and MergedXnode extension

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#1430]
* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
Currently there is two extensions to model the border : Xnode and MergedXnode. These two extensions are not used in the MergingView but should be used to read/store additional data. 

This PR is related to our thinking about the modeling of the borders.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Solved by #2442
