### ISSUE TITLE
[MergingView] BusCache in the index should contains only configured bus

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#1431]
* **Do you want to request a *feature* or report a *bug*?**
Investigation

* **What is the current behavior?**
We have to ensure that the cache in the MergingViewIndex contains only configured bus (i.e. bus created from a Bus/Breaker VoltageLevel). All the calculated bus are transient and should be managed by caches in the voltage levels, depending on the state and the views.
If the index contains both configured and calculated bus, refactor the code to fix this issue. Each time the topology change, we will add new buses in the cache without removing old calculated buses, so we have some kind of a memory leak.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Solved by #2442
