### ISSUE TITLE
[MergingView] Ensure that topology changes are correctly handled

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#1433]
* **Do you want to request a *feature* or report a *bug*?**
Investigation

* **What is the current behavior?**

When the topology change in an IIDM network, the voltage level invalidate the topology and the associated caches. If the network is part of the merging view, the topology of the merging view has to be invalidated (synchronous/connected components).
We also have to support topology changes from the merging view itself, and invalidate the caches of the merging view and the relevant sub network.

Question: is it necessary to invalidate the cache of all the networks?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Solved by #2442
