### ISSUE TITLE
[MergingView] Extension management

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#1435]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
For most of the identifiables objects, we currently delegate the call to getExtension. But as the extension can return the identifiable object, they should be wrapped to return the adapted object, to be able to write:
```
assertSame(identifiable, identifiable.getExtension(Extension.class).getIdentifiable());
```
With the current version of the code, the getIdentifiable() will return the adaptee and not the adapter object.

For some objects, extension management is not working at all:
- DanglingLine extensions are not compatible with Line extensions: how to manage the extension for a MergedLine? If we allow the creation of extensions, we will lose them in the export because the MergedLine is transient. 
- The MergingView could delegate access to the underlying network extensions, but it's possible to have the same extension in several networks. In that case, what is the expected behaviour. Same question about extension creation.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Solved by #2442
