### ISSUE TITLE
[MergingView] some methods are not implemented

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#1436]
* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
Some methods are not implemented yet. We can easily retrieve them because they throw an exception:
```
throw createNotImplementedException();
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
All the API should be implemented: if some method are not supported, we should throw an UnsupportedOperationException.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Solved by #2442
