### ISSUE TITLE
[MergingView] Clean the unused classes/methods

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#1437]
* **Do you want to request a *feature* or report a *bug*?**
Refactoring

* **What is the current behavior?**
Some classes are not used anymore (component management) and can be safely removed.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Solved by #2442
