### ISSUE TITLE
[MergingView] Improve the implementation of some methods

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#1438]
* **Do you want to request a *feature* or report a *bug*?**
Refactoring

* **What is the current behavior?**
Some method implementations could be improved to have better performance or make the code cleaner:
- TerminalAdapter::setRegulatingTerminal: we should introduce a method to get a Termianl from a TerminalAdapter. These lines are duplicated in all the classes that support regulation.
- ValidationUtil::checkUniqueIds(): this method could certainly be optimized to offer better performance.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Solved by #2442
