### ISSUE TITLE
[MergingView] MergingView properties

### ISSUE THREAD

**Issue by miovd** [powsybl/powsybl-core#1454]
* **Do you want to request a *feature* or report a *bug*?**
Almost a bug

* **What is the current behavior?**
When the user looks for a property of the merging view, the value of the property of the first met network is given. What if the property is filled for several networks with different values?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create two networks with a `test` property, one with value `true` and the other with value `false`. Create a mergingview containing these two networks. Use `getProperty("test")` on this mergingview.

* **What is the expected behavior?**
Don't really know yet.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.6.0-SNAPSHOT

**Comment by annetill** [comment]
Solved by #2442
