### ISSUE TITLE
Shunt compensator regulating terminal definition

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-core#1584]
* **Do you want to request a *feature* or report a *bug*?**

Maybe a bug.

* **What is the current behavior?**

I met some difficulties to set the regulating terminal of a `ShuntCompensator`, espacially when it is the local one.  I have to search for another equipment that is connected to the controlled bus. It seems that we don't have this issue with generators. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

To have to possbility to set the local terminal or set the regulating terminal for the local one by default.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by MioRtia** [comment]
After some inspection, it seems that not setting the regulating terminal in the adder makes it local. No further correction is needed.
