### ISSUE TITLE
Network element deep removal

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-core#1857]
* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
When we remove a `Connectable` it only remove the element but does not clean the topology.
For instance with such a voltage level:

![after_creation](https://user-images.githubusercontent.com/632675/137703703-44d55055-ce14-42a7-aa3d-d6c601190000.png)

When a remove the first top conso, we end up with:

![after_removal](https://user-images.githubusercontent.com/632675/137703812-fdf7a52a-3d0f-4a4e-ab86-2d61ddefbd15.png)

* **What is the expected behavior?**

The idea is to be able to clean dangling wires/switches, so we would expected in that case:

![before_creation](https://user-images.githubusercontent.com/632675/137704167-c4815248-42d4-435c-8660-4a41f9df956b.png)

Proposed algorithm: clean switches until the first topology "fork".

Proposed API: an optiona boolean in the `remove` method.
```java
Load l = n.getLoad("L");
l.remove() // just remove the load
l.remove(true) // remove the load and clean the topology
```

Remark: the cleaning will only concern dangling switches, no other connectable can be removed!!!!!

* **What is the motivation / use case for changing the behavior?**
Simplify, network element removal from a user point if view.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
https://github.com/powsybl/powsybl-core/issues/1852

Same kind of need for adding an injection.
