### ISSUE TITLE
Make more IIDM extensions "variants enabled"

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/powsybl-core#1936]
* **Do you want to request a *feature* or report a *bug*?**

Feature.

* **What is the current behavior?**

Some extensions carry data which "look" variant-bound, but which are actually common to all variants, see for instance `ActivePowerControlImpl`.

* **What is the expected behavior?**

The following extensions should be "variants enabled", i.e carry one value for each network variant:
 - `ActivePowerControlImpl`
 - `HvdcAngleDroopActivePowerControlImpl`
 - `HvdcOperatorActivePowerRangeImpl`
 - `CoordinatedReactiveControlImpl`
 - `RemoteReactivePowerControlImpl`
 - `VoltagePerReactivePowerControlImpl` (to be confirmed?)

* **What is the motivation / use case for changing the behavior?**

Being able to use those data in multi-variant processes.

In our actual use case, we need to generate many variant with different HVDC droop values.

**Comment by CBiasuzzi** [comment]
is VoltagePerReactivePowerControlImpl, in the list, confirmed?

**Comment by sylvlecl** [comment]
@annetill or @geofjamg : could you confirm it?

I think it's more something that can be adapted to the operation needs than a structural data?

**Comment by sylvlecl** [comment]
@CBiasuzzi eventually, the VoltagePerReactivePowerControlImpl is NOT to be changed. Its data is more considered as constructor data, than something operational.
