### ISSUE TITLE
Improve full export

### ISSUE THREAD

**Issue by marcosmc** [powsybl/powsybl-core#1958]
* **Do you want to request a *feature* or report a *bug*?**
A feature.
When doing a full export from a pure IIDM Network, the extension CgmesIidmMapping should also be created and filled. It contains mapping data between CGMES and IIDM that should be reused if the same Network is exported again (base voltages, for example). Other mapping information is already been stored as aliases and properties, so it is also reused if re-exporting.
The mapping between Network buses and TNs should be "updated". Currently, it is either read from the extension or created from scratch. If a user imports a Network from CGMES, then creates new buses on the Network, the mapping would became invalid (would miss mappings for the new buses).

* **What is the current behavior?**
See above

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
See above.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Complete.
