### ISSUE TITLE
Network still referenced from a VoltageLevel after removal

### ISSUE THREAD

**Issue by sebalaig** [powsybl/powsybl-core#1960]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
After removing a VoltageLevel from a network, calling `VoltageLevel::getNetwork()` on it still returns the network.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```
    @Test
    public void vlRemove() {
        Network network = Network.create("test", "test");
        network.newVoltageLevel()
                .setTopologyKind(TopologyKind.BUS_BREAKER)
                .setId("bbVL")
                .setName("bbVL_name")
                .setNominalV(200.0)
                .setLowVoltageLimit(100.0)
                .setHighVoltageLimit(200.0)
                .add();
        VoltageLevel voltageLevel = network.getVoltageLevel("bbVL");
        voltageLevel.remove();
        assertNull(voltageLevel.getNetwork());
    }
```

* **What is the expected behavior?**
`VoltageLevel::getNetwork()` should return null.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by miovd** [comment]
Thank you for this issue! It also seems this issue exists for all `Identifiable` in `iidm-impl`. This should indeed be corrected.
