### ISSUE TITLE
Improvements on CGMES 3.0 export

### ISSUE THREAD

**Issue by miovd** [powsybl/powsybl-core#2047]
* **Do you want to request a *feature* or report a *bug*?**
CGMES 3.0 export is now an alpha feature. There are still some issues to solve.

* **What is the current behavior?**

Known issues:

    - GeneratingUnit.initialP should not be exported.
    - OperationalLimit TypeName should be exported in a different way (eu extension instead of entsoe).
    - OperationalLimit value should be exported as normalValue.
    - Every object should have mRID exported, in addition to rdf:ID (the mRID does not require a _ prefix).

Linked comment https://github.com/powsybl/powsybl-core/pull/1998#issuecomment-1081681530

* **Please tell us about your environment:**
  - PowSyBl Version: 4.8.0-SNAPSHOT

**Comment by zamarrenolm** [comment]
Solved as the required changes initially prepared in #2059 have been included in #2091
