### ISSUE TITLE
[CGMES] Fill ENTSOE category extension 

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/powsybl-core#2103]
* **Do you want to request a *feature* or report a *bug*?**

Feature.

* **What is the current behavior?**

We have a `GeneratorEntsoeCategory` extension, but it's not created when importing a CGMES file.
The information is lost.

* **What is the expected behavior?**

We should retrieve that information and create the extension to expose it to the user.

* **What is the motivation / use case for changing the behavior?**

pypowsybl users expected to have that information filled in, when importing a CGMES file.

@zamarrenolm : would you know how to retrieve that information ?

**Comment by geofjamg** [comment]
Convergence get it by parsing the description field of generating units... No idea if it is an official hack agreed by everybody.

**Comment by zamarrenolm** [comment]
I planned to write it as a post-processor, instead of adding the "hack" directly to conversion, as it seems it is something not really standardized. Any thoughts on that ?

**Comment by geofjamg** [comment]
> I planned to write it as a post-processor, instead of adding the "hack" directly to the conversion code, as it seems it is something not really standardized. Any thoughts on that ?

Good idea!
