### ISSUE TITLE
Implementation of HVDC set point change action

### ISSUE THREAD

**Issue by Hadrien-Godard** [powsybl/powsybl-core#2175]
* **Do you want to request a *feature* or report a *bug*?**
Feature.

* **What is the current behavior?**
The action is not implemented.

* **What is the expected behavior?**
The HVDC set point change action is implemented as an implementation of the Action class (see issue #2015).
This action consists in changing the set point of an HVDC line.
A starting idea of possible implementation is:
```java
class HvdcPointChangeAction extends Action {
    String hvdcId;
    double setPointValue;
}
```

* **What is the motivation / use case for changing the behavior?**
Allow security analysis to take this action type into account.

**Comment by annetill** [comment]
Solved by #2454
