### ISSUE TITLE
Empty child reporter management

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-core#2192]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
A major issue I had using reporter API is that I often end up with empty child reporter, because some reports that could go inside this reporter are optional (and depending of running case).
One easy but bad answer to that is to state that this is up to reporter API user to handle this case and anticipate future empty reporter. This would be wrong because it is just impossible in most of the cases to know when creating the container (the reporter) how many reports will go inside. 
All these empty reporters decrease final readability.

* **What is the motivation / use case for changing the behavior?**
I can see 2 possible solutions (probably there is more):
 1) provide in the `Reporter` a cleanEmptyChildren method to clean everything at the end
```java
reporter.cleanEmptyChildren()
```

 2) just handle empty reporters in the serialization with an option like:
```java
reporter.write(true)
```

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by flo-dup** [comment]
There's no difference between `Reporter` and `Report` anymore: there's only `ReportNode`s which may or may not contain children
