### ISSUE TITLE
Reporter variable context inheritance

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-core#2193]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
When formatting reports, we should be able to use
 1) variables of the report
 2) variable of all parent reporters

!!!! In the actual text formatter, we only use variables of the report and the ones of first parent reporter.

This would be a huge improvement in term of compactness of report as it would be possible to store common variables in a common reporter ancestor and no need to repeat it in all child reporters.

* **What is the expected behavior?**

The evolution is:
 1) mostly a matter of documentation of the API to describe that it is allowed to define variables in any parent of a reporter and that all formatters should take them into account.
 2) implement it in default text formatter as a demonstrator.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by flo-dup** [comment]
Following a discussion with @laurgarn I'm wondering if we shouldn't also do the opposite, at least for a depth of one. Why? because the title cannot contain results which are in its child messages, and even if this node is not expanded we might want to display some concise info about what happened within.

**Comment by laurgarn** [comment]
@flo-dup aggregation/synthetis might be simpler/more flexible on the front-end (that's what is done in Convergence, where transmitted contexts don't have a status level by themselves).
Of course back-end aggregation might be more powerful but yet I can only think of worst child status as a standard aggregation rule. May be overall processing time, but this is not as easy as in C++.
On the other side, front-end could have parameters to aggregate differently the same back-end provided data.
