### ISSUE TITLE
Create utility class for compareXml/compareTxt

### ISSUE THREAD

**Issue by miovd** [powsybl/powsybl-core#2208]
* **Do you want to request a *feature* or report a *bug*?**
Refactoring

* **What is the current behavior?**
Utility classes `compareXml` and `compareTxt` are in `AbstractConverterTest`

* **What is the expected behavior?**
These methods should be in a utility class `ComparisonUtils`

* **What is the motivation / use case for changing the behavior?**
Cleaner design

* **Please tell us about your environment:**
  - PowSyBl Version: 4.10.0-SNAPSHOT

**Comment by sfid98** [comment]
Hi @miovd,
I have worked to this issue in this PR: 
[#2209 ](https://github.com/powsybl/powsybl-core/pull/2209)
Please take a look, this is my first contribution and I hope that the changes are good 
Thank you
