### ISSUE TITLE
CGMES Exporter misses attributes for Power Transformers

### ISSUE THREAD

**Issue by AnkurArohi** [powsybl/powsybl-core#2258]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**

This is regarding CGMES Exporter in powsybl and also in pypowsybl,
I have noticed that the PowerTransformerEnd is missing attribute ratedS and also base voltage

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

This is what I have done
Import CGMES profile, run a power flow and export CGMES Profile, the exported CGMES Profile from powsybl is ignoring the ratedS attribute which was originally present in the initial CGMES profile

**What is the expected behavior?**

Attributes like ratedS and basevoltage cannot be ignored when exporting CGMES from powsybl network

**What is the motivation / use case for changing the behavior?**

CGMES Exporter to be consistent with the CIM 16 standards

Please tell us about your environment:

PowSyBl Version: ...
OS Version: ...
Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by miovd** [comment]
`ratedS` now exported (#2265)
`BaseVoltage` attribute to be resolved
