### ISSUE TITLE
CGMES Exporter misses Voltage level reference for Synchronous Machines

### ISSUE THREAD

**Issue by AnkurArohi** [powsybl/powsybl-core#2261]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**

Currently, powsybl CGMES Exporter is not able to reference the voltage level for the Synchronous Machines

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Load a CGMES Profile with the reference of voltage level provided for synchronous machine and then export it,then compare the original Synchronous machine tag with the exported one from powsybl

* **What is the expected behavior?**

Analog to the original CGMES profile all synchronous machines should have a voltage level referenced through "cim:Equipment.EquipmentContainer"

* **What is the motivation / use case for changing the behavior?**

CGMES Exporter to follow CIM 16 standards

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by miovd** [comment]
Resolved by #2265
