### ISSUE TITLE
`org.antlr:stringtemplate` is Faulty

### ISSUE THREAD

**Issue by aryeh-looker** [powsybl/powsybl-core#2300]
`org.antlr:stringtemplate` relies on `org.antlr:antlr-runtime`, which has a circular dependency back on `org.antlr:stringtemplate`. Maven can gracefully deal with the misconfiguration, but some build tools like bazel cannot; e.g. https://github.com/aryeh-looker/bazel-circular-deps. I believe it is possible to write the `pom.xml` to resolve this circular dep, so that users of `powsybl-core` and other build systems do not need to .

**Comment by geofjamg** [comment]
Thanks for reporting this issue. It will be fixed by #2301 in next release.

**Comment by miovd** [comment]
Resolved by #2301
