### ISSUE TITLE
Add a method to retrieve the neutral step of a tap changer

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-core#2362]
* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

Nothing exists.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

A method that retrieves the neutral step of a tap changer:
- for ratio tap changer, the step with a rho equals to 1
- for phase tap changer, the step with an angle equals to 0.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by miovd** [comment]
Fixed by #1897
