### ISSUE TITLE
Client connections

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-core#2364]
* **Do you want to request a *feature* or report a *bug*?**

A feature. We miss hypotheses to simulate a client connection to the network. I know, for the moment, two kinds of connections:
- A simple connection, in an existing line, where we have to create a voltage level from the network (and not from the substation). In that connection, there is no breaker at all. 
- A connection with breakers, as explain here file:///D:/Users/tilloyann/Downloads/190404_2019-076_ProcedureProducteursRTE_annexe.pdf page 31. The connection is still in the middle of a line, but with three breakers: two for the existing line and one for the client.

We are the list of the needed features:
- Create a simple connection from a Line ;
- Create a connection with breakers from a Line ;
- Convert a simple connection to a connection with breakers ;
- Convert a connection with breakers to a simple connection.

* **What is the current behavior?**

Nothing exists for the moment.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by miovd** [comment]
Fixed by #2214 and #2257
