### ISSUE TITLE
Refactoring of CGMES Metadata extensions and metadata properties

### ISSUE THREAD

**Issue by miovd** [powsybl/powsybl-core#2384]
* **Do you want to request a *feature* or report a *bug*?**
Enhancement

* **What is the current behavior?**
Some CGMES metadata are imported in properties, other in different extensions `CgmesSvMetadata` and `CgmesSshMetadata`

* **What is the expected behavior?**
It would be great to have one extension containing all the CGMES metadata.

* **What is the motivation / use case for changing the behavior?**
It will be easier to know where to retrieve the informations.

* **Please tell us about your environment:**
  - PowSyBl Version: 5.1.0-SNAPSHOT

**Comment by zamarrenolm** [comment]
Closed after changes that implement CGMES metadata models extension: #2898, #2988.
