### ISSUE TITLE
Replace Halfline by DanglingLine

### ISSUE THREAD

**Issue by miovd** [powsybl/powsybl-core#2422]
* **Do you want to request a *feature* or report a *bug*?**
Feature / Model modification

* **What is the current behavior?**
`TieLine` is composed of two `HalfLine`

* **What is the expected behavior?**
`TieLine` should be composed of two `DanglingLine.

* **What is the motivation / use case for changing the behavior?**
It would allow to merge and unmerge TieLine more easily without any loss of information.

* **Please tell us about your environment:**
  - PowSyBl Version: 5.1.0-SNAPSHOT

**Comment by annetill** [comment]
Solved by #2437
