### ISSUE TITLE
Allow revert of merge of networks

### ISSUE THREAD

**Issue by miovd** [powsybl/powsybl-core#2423]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
You can merge several networks but if you eventually want to get them back, you either have to copy them beforehand or to use the merging view.

* **What is the expected behavior?**
It would be great to be able to get back the underlying networks via an `unmerge` (?) method in `Network` returning the list of the underlying networks.

* **What is the motivation / use case for changing the behavior?**
Due to the difficulty to maintain the MergingView and even the lacks the implementation presents, it would be better to avoid using it and prepare its removal. To do so, we have to propose an alternative solution to reproduce its features.

* **Please tell us about your environment:**
  - PowSyBl Version: 5.1.0-SNAPSHOT

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

**Comment by annetill** [comment]
Solved by #2442
