### ISSUE TITLE
Sensitivity analysis threshold

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-core#2496]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
We cannot filter very low sensitivity values.

* **What is the expected behavior?**
We should be able to define in `SensitivityAnalysisParameter` 4 thresholds (double values):
  - flowFlowSensiValueThreshold
  - voltageVoltageSensiValueThreshold
  - flowVoltageSensiValueThreshold
  - angleFlowSensiValueThreshold

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
@annetill @Hadrien-Godard @jeandemanged is it ok for you?

**Comment by Hadrien-Godard** [comment]
> @annetill @Hadrien-Godard @jeandemanged is it ok for you?

Yes

**Comment by obrix** [comment]
@geofjamg @Hadrien-Godard What should be the default values for those parameters ? 0.0 for no filtering ?

**Comment by geofjamg** [comment]
I would say 0 which would mean not filtering
