### ISSUE TITLE
CGMES: SynchronousCondensers are not imported

### ISSUE THREAD

**Issue by jeandemanged** [powsybl/powsybl-core#2606]
### Describe the current behavior

cim:SynchronousMachine-s with type `SynchronousMachineKind.condenser` are not imported in iIDM

### Describe the expected behavior

Synchronous condensers should be imported in iIDM

### Describe the steps

- Load a CGMES with a cim:SynchronousMachine with type `SynchronousMachineKind.condenser`. **As per [QoCDC](https://eepublicdownloads.azureedge.net/clean-documents/digital/QualityOfCGMESdatasetsAndCalculations_v3_3.pdf) rule `SynchronousCondenser` (line 2626), the SynchronousMachine should not have any cim:GeneratingUnit associated.**
- check iIDM content, the condenser cannot be found

### Environment

powsybl-core:5.2.1

### Extra Information

It seems that the SPARQL query for synchronous machines assumes that a GeneratingUnit is always present for SynchronousMachines, but this isn't true for condensers - hence query is missing the condensers. `cim:RotatingMachine.GeneratingUnit` should be considered optional in query, or another dedicated query should be made for condensers.

**Comment by zamarrenolm** [comment]
I think it will be clearer if we make a specific separate query for synchronous machines than can only be "condensers". For the rest of types (generator, motor and its combinations) we should always have an associated generating unit.
