### ISSUE TITLE
New short circuit parameters

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-core#2643]
### Describe the current behavior

The parameters are a bit poor. 

### Describe the expected behavior

New parameters could be added:

- `withLoads`: a boolean. If set to `true` means that loads are taken into account in the short-circuit calculation by using `P0` and `Q0` to retrieve the short-circuit feeding. If set to `false`, all loads are considered with `P0` and `Q0` equal to zero. 
- `withShuntCompensators`: a boolean. If set to `true` means that shunt compensators feeding is taken into account. `Q` and `P` are used to retrieve the short-circuit feeding. `False` means no feeding. 
- `withVSCconverterStations`: same logic. 

Note that for these three parameters, it could be interesting to have the formula or mode details on the equivalent modeling. 

- `withNeutralPositon` for tap changers only. If `false`, the step defined in the network model is used, else the neutral step is used (rho = 1, alpha = 0).
- 
-  Initial voltage profile: using nominal voltages, configured with a list of <Nominal voltage value, coefficient> or previous value. we can imagine at least an enum `NOMINAL`, `CONFIGURED` and `PREVIOUS_VALUE`. The hardest part is to defined how to configure.We have in the `yml` file two options:
1) We ask for low and medium voltage definition + three coefficient : one for low voltage, one for medium voltage and one for high voltage as used here:
https://github.com/powsybl/powsybl-incubator/blob/main/simulator/short-circuit/src/main/java/com/powsybl/incubator/simulator/shortcircuit/ShortCircuitNormIec.java
2) Or something more generic (but I don't know how to design that in the configuration file):
- {380 ; 420} -> coefficient 
- {200 ; 245} -> coefficient 
- etc...

**Comment by colinepiloquet** [comment]
For the shunts, I think that if the boolean is true, a load is created linked to the shunt. And that B of the shunt is used for the load characteristics.

**Comment by colinepiloquet** [comment]
Fixed in #2638
