### ISSUE TITLE
Force CGMES import to bus/breaker topology

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-core#2700]
### Describe the current behavior

Sometimes, IGMs in CIM-CGMES are in node/breaker topology. But in these files, we have just a small number of breakers (in general just between bus bar sections). The consequence are multiple. For example, a line contingency with propagation could lead to the loose of many equipments. The line cannot be opened also. In IIDM, this kind of description are typically the bus/breaker topology. 

### Describe the expected behavior

We would like a parameter in CGMES import that forces to import a file in bus/breaker topology. We have a solution (removing the Operation profile) but it is time costly.

**Comment by jeandemanged** [comment]
Great idea, also note that in European Merging Function context, EMF is not supposed to recompute topology / rebuild topological nodes. Therefore forcing bus-breaker import is also a valid use case here.

**Comment by zamarrenolm** [comment]
Ok to add the parameter.
I assume that you want the bus/breaker level be created from Topological Nodes in the input (TP file must be present, then).
