### ISSUE TITLE
DynamicSimulationResult

### ISSUE THREAD

**Issue by Lisrte** [powsybl/powsybl-core#2772]
### Describe the expected behavior

Remove log field  -> use DynamicSimulationProvider reporter instead
Replace status field -> use Status enum with description of the error copied from dynawo error report
Replace StringTimeSeries field with a adequate TimeSeries 

### Describe the motivation

Match Dynawaltz implementation

**Comment by flo-dup** [comment]
After discussing with @geofjamg
- as the reporter cannot be well formatted with dynawo current output log file, we might need to keep the log field, I'll give you a feedback on that later
- ok for status field with enum + reason
- you can replace StringTimeSeries with a List<TimeLineEntry>, or a TimeLine object containing that list
