### ISSUE TITLE
RemoveFeederBay does not remove linked switches  when a component is removed from a busbreaker model

### ISSUE THREAD

**Issue by marqueslanauja** [powsybl/powsybl-core#2880]
### Describe the current behavior

In `busBreaker` models, when I remove a `ground` component that is connected to the `main bus` throughout a `breaker`, only the `ground` component is removed. The `breaker` and the `bus` where the `ground` was connected remain in the model.

### Describe the expected behavior

The` breaker` and the `bus` where the `ground` was connected have also to be removed.

### Describe the steps

#2879 includes a unitary test reproducing the bug.

Diagram of the model before removing the ground

![image](https://github.com/powsybl/powsybl-core/assets/51124986/8db4fb9f-e5cb-43c1-8acf-ffa391879f6f)

Diagram of the model after removing the ground

![image](https://github.com/powsybl/powsybl-core/assets/51124986/556243ee-a49e-4fa0-a510-19fe04235f68)

**Comment by annetill** [comment]
To be confirmed by @flo-dup but I think it is the normal behavior.

**Comment by flo-dup** [comment]
yes, this is the "normal" behavior: in bus breaker view, RemoveFeederBay only disconnects the equipment.

Which behaviour would you expect? Similarly to node breaker view, removing all breakers and buses until you encounter a fork or another equipment?

**Comment by marqueslanauja** [comment]
> yes, this is the "normal" behavior: in bus breaker view, RemoveFeederBay only disconnects the equipment.
> 
> Which behaviour would you expect? Similarly to node breaker view, removing all breakers and buses until you encounter a fork or another equipment?

Yes. This is the behaviour that I expect.

**Comment by flo-dup** [comment]
I confirm that it is normal behaviour, this modification should not remove a bus in bus/breaker view (or, similarly, a busbar section in node/breaker view). Confirmed in technical meeting today.
