### ISSUE TITLE
CGMES import: use reference priority extension

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-core#2900]
### Describe the current behavior

![image](https://github.com/powsybl/powsybl-core/assets/48123713/b571f089-8027-401d-a167-059eac5c1900)

The reference priorities in CGMES are dedicated to angle reference bus modeling, not slack bus modeling. 

### Describe the expected behavior

I think that we have to fix the CGMES importer to fill for a generator for example:
````
    <iidm:extension id="G">
        <refpri:referencePriorities>
            <refpri:referencePriority priority="1" id="G"/>
        </refpri:referencePriorities>
    </iidm:extension>
````

**Comment by zamarrenolm** [comment]
Yes, CGMES import/export has to be updated after #2763. The previous issue #2747 could be closed and replaced by this one.
