### ISSUE TITLE
Concurrent use of Network instances (thread-safety)

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/powsybl-core#300]
The concurrent use of a NetworkImpl object, even with the multi-thread state manager, is partly broken:

underlying containers such as BitSet or TFloatArrayList are not thread-safe, meaning that for exemple extending it in 1 thread while writing to it in another thread may result in unexpected behaviour (exceptions, or corrupt data).

Several solutions may be foreseen:
- make the network fully thread-safe by switching to thread-safe implementations of those collections. The performance cost needs to be evaluated
- declare the API as not thread-safe and have client code handle it
- guarantee thread-safety except for state cloning operations : require to remove use of BitSet, and to provide a kind of lock to ensure that no cloning operation is run while using the Network

**Comment by mathbagu** [comment]
Fixed in #535
