### ISSUE TITLE
Operational limit setters

### ISSUE THREAD

**Issue by colinepiloquet** [powsybl/powsybl-core#3060]
### Describe the current behavior

There are no setters for `TemporaryLimits` which means that to modify one value the whole limit must be recreated. 

### Describe the expected behavior

I think it would we useful to be able to set some of the attributes of the temporary limits, especially the `value`. 

### Describe the motivation

It would be useful to correct faulty data without having to store all the temporary limits and recreate the whole limit.

**Comment by nao1345678** [comment]
To correct an already existing limit, we have to make sure the new value fits logically in between the already existing other temporary limits. 
For instance, if the new value is greather than the next one, shouldn't we change the acceptable duration too ? Or should we change the limits' order ?

**Comment by colinepiloquet** [comment]
Maybe it's enough to check the other values and if the new limit does not fit logically then the correction would not work ?

**Comment by olperr1** [comment]
When a `LoadingLimits` is created, we only log warnings when the temporary limits' values are not consistent (see [`ValidationUtil.checkTemporaryLimits(...)`](https://github.com/powsybl/powsybl-core/blob/4b65c5f45dfdae814350c4e30a2d6d6b1fe4c7f2/iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java#L572)).
I think that we can adopt the same principle: allow the inconsistent values, but log warnings in that case.
