### ISSUE TITLE
Be able to disconnect a line from another one 

### ISSUE THREAD

**Issue by pgambier** [powsybl/powsybl-core#3236]
### Describe the current behavior

When disconnecting a Line the graph traversal do not look for connections between two Connectable (2 lines) therfore do not disconnect themselves.

In the case of a fork like the image below if we want to disconnect the first line it is still connected to the second line.
![Fork](https://github.com/user-attachments/assets/b954da77-0cdb-4563-98c8-f665946a7684)

### Describe the expected behavior

In the case of a fork like the image above if we want to disconnect the first line then it should no longer be connected to the second line. The highlighted switch should be open.

### Describe the motivation

Be able to isolate a line from another one.

**Comment by flo-dup** [comment]
What do you think should occur when calling `connect()` for a fork @pgambier? if the disconnector of the other line and the bbs switch are opened.
With a diagram, that may be clearer; with the voltage level below, if calling connect on line L2, should the breaker only be closed after, or should also the line L1 be connected?
![screenshot](https://github.com/user-attachments/assets/4dce91ca-0263-414b-9eb2-6eb665ca9bc2)

**Comment by pgambier** [comment]
I think we should split the issue and fix the disconnect part only in this one
