### ISSUE TITLE
 Traverser traverses all edges

### ISSUE THREAD

**Issue by alicecaron** [powsybl/powsybl-core#3241]
### Describe the current behavior

According to javadoc UndirectedGraphImpl::traverse(int v, Traverser t) should traverse the entire graph. It traverses all the vertices but not all the edges.

### Describe the expected behavior

UndirectedGraphImpl::traverse(int v, Traverser t) traverses all the vertices and all the edges of the graph.

### Extra Information

The original merge request [core#2341](https://github.com/powsybl/powsybl-core/pull/2341) introduces a duplicate in the list of the traversed nodes. Either:
   - Use a TIntHashSet instead of a TIntArrayList for nodes
   - or keep the nodes duplication but remove the duplicates when building the Terminals CopyOnWriteArrayList
   - other solution?

Add unit test to cover the loop case, when multiple path exist between two vertices.

**Comment by flo-dup** [comment]
A third proposal is what's been done in #3242, that is reuse the existing `encounteredVertices` array which is used and maintained in `UndirectedGraph::traverse`. This is an easy fix and it has no impact on performance, as it was already computed.
