### ISSUE TITLE
In CIM1 converter warnings should go after trying to add synchronous machines to the Network

### ISSUE THREAD

**Issue by zamarrenolm** [powsybl/powsybl-core#58]
Warnings emitted for non-empty collections `synchronousMachinesWithoutRegulatingControl`, `synchronousMachinesRegulatingVoltageWithZeroTargetVoltage`, `synchronousMachinesWithReactiveRangeForMinus9999MW` are made BEFORE code that tries to add to the `Network` the synchronous machines found in CIM, where these collections could be eventually filled in.

The warnings should go AFTER calls to `createGenerator` are made.

**Comment by mathbagu** [comment]
Fixed in #118
