### ISSUE TITLE
Autoservice and guava update

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#659]
Consider update the version of `com.google.auto.service:auto-service` to a version greater than `1.0-rc4`. It requires to update `com.google.guava:guava` from 20.0 to 21.0 (at least).

There is also an issue in `powsybl-afs-mapdb-storage` that depends on `org.mapdb.mapdb` (3.0.3) that requires a version of guava older that 19.20:
```
<guava.version>[15.0,19.20)</guava.version> 
```
This issue is solved since MapDB 3.0.6

Guava is also used in cassandra.

**Comment by MioRtia** [comment]
Fixed by #1366
