### ISSUE TITLE
Use Java9 newIncompleteFuture of CompletableFuture to ease LocalComputationManager canceling

### ISSUE THREAD

**Issue by jonenst** [powsybl/powsybl-core#667]
Right now when using LocalComputationManager, the only CompletableFuture that kills the external process and interrupts the thread is the one that was returned by the call to execute. If you cancel new CompletableFuture created by chaining computations, it does not do it.

Using newIncompleteFuture from Java9 would allow the chained CompletableFuture to be of our subclass and have the interrupting behavior.

**Comment by geofjamg** [comment]
Solved by #2051
