### ISSUE TITLE
Add convenient methods to get P, Q, V and angle

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#678]
* **Do you want to request a *feature* or report a *bug*?**

Feature.

* **What is the current behavior?**

To get `P`, `Q`, `V` and `angle`, a developer has to know that these information are only available on the terminal:
```
double p0 = network.getLoad("LOAD_ID").getP0();
double p = network.getLoad("LOAD_ID").getTerminal().getP();
```
It should also be possible to get easily the Network from a connectable:
```
Network network = load.getTerminal().getVoltageLevel().getSubstation().getNetwork();
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

N/A

* **What is the expected behavior?**

Be able to write this code:
```
double p0 = network.getLoad("LOAD_ID").getP0();
double p = network.getLoad("LOAD_ID").getP();
double p1 = network.getLine("LINE_ID").getP1();
double p2 = network.getLine("LINE_ID").getP2();

Network network = load.getNetwork();
```

* **What is the motivation / use case for changing the behavior?**

It seems more natural to be able to get these values from the connectable itself. Could we add some convenient methods in the IIDM API.

* **Please tell us about your environment:**
  - PowSyBl Version: 2.3.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by geofjamg** [comment]
So what you want here is to remove terminal concept from IIDM API? because I do feel it would be a good idea to give to possibility to access same data from 2 differents places in the data model.

**Comment by mathbagu** [comment]
No I just want to have convient methods on connectable to get these values. I hard to explain to someone the Terminal concept, specially to beginners with powsybl. This request has been made several times to me, Terminal concept seems not so easy to understand

**Comment by geofjamg** [comment]
If terminal concept is too hard to understand we can simply remove it from the API. The worst solution for me is to keep 2 way to get the same data, it would just be a mess.
```java
network.getLine("LINE_ID").getTerminal1().getP();
network.getLine("LINE_ID").getP1();
```
So why not just keeping only second line.

**Comment by geofjamg** [comment]
And also it would be consistent with xml/json serialization

**Comment by annetill** [comment]
Can I close this issue ? For me, the `Terminal` object is needed to understand the sign convention. And now, for users we provide the framework in pypowsybl where we have these shortcuts.
