### ISSUE TITLE
Scalable without equipment reconnection

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-core#716]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
When scaling generator or load using Scalable API, the equipment is automatically connected and is part of the scaling.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
This behavior is sometimes what we want, but there is other use cases for which (some) equipment should not be reconnected and should be excluded from the scaling. 

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: 2.5.0-SNAPSHOT
  - OS Version: Linux

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

(if a question doesn't apply, you can delete it)

**Comment by annetill** [comment]
Solved !
