### ISSUE TITLE
Move mpi computation manager to powsybl-hpc repository

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-core#745]
* **What is the motivation / use case for changing the behavior?**

MPI computation manager is in core repository but:
  - it is not widely used, as it requires a HPC cluster
  - it needs native code compilation

To move:
 - computation-mpi Maven module
 -  mpi-communication and jni-util CMAKE modules
 - install.sh ?

After that only KLU will requires native code compilation. Do we move KLU as the same time ? And where ?

**Comment by sylvlecl** [comment]
MPI computation manager has been moved to powsybl-hpc, see #858 .
