### ISSUE TITLE
Deprecate RatioTapChanger and PhaseTapChanger and only use one class TapChanger

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-core#801]
* **Do you want to request a *feature* or report a *bug*?**
Refactoring

* **What is the current behavior?**
`RatioTapChanger` is actually a `PhaseTapChanger` with a null phase shift (alpha)

* **What is the expected behavior?**
Have only one class `TapChanger` with rho and alpha

* **What is the motivation / use case for changing the behavior?**
Simplify the API

* **Please tell us about your environment:**
  - PowSyBl Version: 3.0.0-SNAPSHOT

**Comment by geofjamg** [comment]
In the actual implementation the  concept of tap changer include the tap table but also some regulation information like in the case of ratio tap changer voltage target or in the case of  phase tap changer the mode and the current limit, etc.
That means ratio and phase tap changer cannot be merge as it is.
Maybe we could start to split each of the tap changer into 2 parts
  - the tap table part
  - the controller part (for voltage control or phase shift control)

and then the tap table part could be shared with a unique table allowing complex ratio.
