### ISSUE TITLE
VariantManagerImpl.removeVariant can have O(N^2) performance

### ISSUE THREAD

**Issue by jonenst** [powsybl/powsybl-core#809]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
VariantManagerImpl.removeVariant can have O(N^2) performance

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```java
    @Test
    public void testManyVariantsN2() throws Exception {
      Network network = new NetworkImpl("test", "test", "test");
      List<String> names = IntStream.range(0,100000)
        .mapToObj(Integer::toString)
        .collect(Collectors.toList());
      network.getVariantManager().cloneVariant( 
          VariantManagerConstants.INITIAL_VARIANT_ID,
          names
      );  
      //Collections.reverse(names);
      for (String name: names) {
        System.out.println("remove" + name);
        network.getVariantManager().removeVariant(name);
      }   
        System.out.println("done");
```
This test takes 30s to execute. If you uncomment the Collections.reverse() call, it takes 2s. 

* **What is the expected behavior?**
It should always be fast.

* **What is the motivation / use case for changing the behavior?**
Fix performance

* **Please tell us about your environment:**
  - PowSyBl Version: 2.5
  - OS Version: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

VariantManagerImpl uses an ArrayDeque and when removing the last element, it does an O(N) call to ArrayDeque.remove for all previously removed variant.
I think using a self balanced binary tree allows to do this in O(log(N)) and allows to add/remove elements at the end in O(log(N)) instead of O(1).. We should also use the tree to get the highest remaining index instead of scanning the indices from the end until one is not set.

**Comment by geofjamg** [comment]
Has been fixed
