### ISSUE TITLE
Update mapDB version

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#816]
* **Do you want to request a *feature* or report a *bug*?**
bug?

* **What is the current behavior?**
There is a mismatch in the guava version between google autoservice (see #659) and mapdb. The guava version is limited between 15 and 19.20 and we require the 20.0.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Method Predicated.checkArgument(boolean, String, int) not found with a version lesser than 20.0

* **What is the expected behavior?**
Should works ^^'
We should update mapdb to 3.0.6 or higher

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: 2.5.0 and older
  - OS Version: Linux

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by MioRtia** [comment]
Fixed by #825
