### ISSUE TITLE
Addition of a storage version in NodeInfo serialization within MapDB

### ISSUE THREAD

**Issue by niconoir** [powsybl/powsybl-core#831]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Currently, no information is serialized in NodeInfo within MapDB about how the data have been serialize and how to deserialize them.

* **What is the expected behavior?**
A new information (storage version) has to be serialized in NodeInfo serialization within MapDB in order to know how the data have been serialized and how to deserialize them.

* **What is the motivation / use case for changing the behavior?**
NodeInfo class will evolve in order to add new informations about the AFS node (see #827 for example). Thus, serialization of NodeInfo within MapDB will evolve, and we need to know how NodeInfo we are reading in MapDB has been serialized in order to deserialize it properly. A storage version included in the NodeInfo serialization will allow us to keep track of the different ways the NodeInfo have been serialized and to deserialize them properly. This will allow us to keep a backward compatibility and deserialize data from older versions from MapDB.
N.B: When this feature will be implemented, the data previously stored in MapDB will not be compatible with the new version.

**Comment by geofjamg** [comment]
AFS is not part anymore of core
