### ISSUE TITLE
IIDM Three Windings Transformer  refactoring in view of CGMES conversion

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-core#848]
* **Do you want to request a *feature* or report a *bug*?**
Neither, it is a model evolution.

* **What is the motivation / use case for changing the behavior?**
The current model is not neutral enough to deal with all t3e configuration at the european level.

* **Please tell us about your environment:**
  - PowSyBl Version: 2.5.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by zamarrenolm** [comment]
Current modelling proposal is being implemented in branch [iidm_three_windings_transformer_refactoring_v2](/powsybl/powsybl-core/tree/iidm_three_windings_transformer_refactoring_v2).

Associated updated CGMES conversion is being refactored in branch [extended_cgmes_conversion_v2](/powsybl/powsybl-core/tree/extended_cgmes_conversion_v2).
