### ISSUE TITLE
Binary network format for efficient exchanges (Apache AVRO, protobuf ...)

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/powsybl-core#894]
* **Do you want to request a *feature* or report a *bug*?**

Feature.

* **What is the current behavior?**

The network model serialization and deserialization to XML is not compact and pretty slow.
This may hamper the performance of distributed computations. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Writing down and reading a large network (say 10000 buses) may take as much as 20 seconds on one modern CPU core (and in-memory or SSD hard drive).
The size of the corresponding XML file is 100Mb.

* **What is the expected behavior?**

We should try to have more size-efficient and CPU-efficient serialization.
In order to achieve this, we may investigate using apache AVRO, or the more well known google protobuf. See an interesting comparison [here](https://labs.criteo.com/2017/05/serialization/) by criteo.

* **What is the motivation / use case for changing the behavior?**

Having more efficient exchanges, in particular for distributed computation.

**Comment by geofjamg** [comment]
@flo-dup thanks to #2307 we will be able to implement this more easily
