### ISSUE TITLE
Use TableFormatter instead sirocco-text-table-formatter

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#90]
Table generation should be done through the TableFormatter API (commons module).

**Comment by mathbagu** [comment]
- Refactor `com.powsybl.iidm.network.util.Networks.java` to use an `AsciiTableFormatter`
- Refactor `com.powsybl.simulation.ImpactAnalysisTool` to use an `AsciiTableFormatter`
- Refactor `com.powsybl.action.simulator.loadflow.LoadFlowActionSimulatorLogPrinter` to use an `AsciiTableFormatter`
- remove the sirroco dependency from iidm-api

**Comment by ChamseddineBhd** [comment]
see #547
