### ISSUE TITLE
Change of Shunt Compensator IIDM model

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-core#900]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Only one type of shunt compensator is represented. Some are not, e.g. non linear shunt compensators. Furthermore, regulating controls are not taken in account with current modeling.

* **What is the expected behavior?**
To be able to model different sort of shunt compensators and to add regulating control

* **What is the motivation / use case for changing the behavior?**
CGMES models shunt compensators with different behaviours and regulating controls.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.0.0-SNAPSHOT

**Comment by geofjamg** [comment]
I would go for a solution where model is dissociated to the equipment (which will be responsible mainly for connectivity)

```java
ShuntCompensator sc = ...
ShuntCompensatorLinearModel model = sc.getModel(ShuntCompensatorLinearModel.class);
double b = model.getbPerSection();
```
