### ISSUE TITLE
New security-analysis API

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#916]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Security-analysis API could be improved and could be more user friendly.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
Create an API that looks like to the new LoadFlow API:
```
SecurityAnalysisResult result = SecurityAnalysis.run(network, contingencyList, new SecurityAnalysisParameters());

SecurityAnalysisResult result = SecurityAnalysis
        .withInterceptors(...)
        .run(network, contingencyList, new SecurityAnalysisParameters());
```

People should be able to pass some parameters to the `SecurityAnalysis` runner (a `SecurityAnalysis.Runner` instance). This runner will handle the required data for the pre and post processing.

* **What is the motivation / use case for changing the behavior?**
Having a more friendly security analysis API.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
Done
