### ISSUE TITLE
TimeSeries csv import fails with quoted values

### ISSUE THREAD

**Issue by pl-buiquang** [powsybl/powsybl-core#978]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
TimeSeries.parseCsv fails with csv using quoted values

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Try to import a csv with quoted values, eg. :
```
"Time","Version",...
```

* **What is the expected behavior?**
successful import

* **What is the motivation / use case for changing the behavior?**
Handling user input generated with python csv lib 

* **Please tell us about your environment:**
  - PowSyBl Version: 3.0.0-SNAPSHOT, 2.6
  - OS Version: Linux, Windows

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
Maybe use a library to handle csv (http://super-csv.github.io/super-csv/ is already in the dependencies).

**Comment by geofjamg** [comment]
We already had same issue recently with `StringAnonymizer` which has been switched to Super CSV which support quoting. 
Maybe it should be considered as a more general issue in PowSyBl as there is probably other CSV parsing with same bug.
