### ISSUE TITLE
connectableBus throws exception in topology calculated from node-breaker all switches open

### ISSUE THREAD

**Issue by zamarrenolm** [powsybl/powsybl-core#981]
* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
Exception is thrown when `BusView` of a `Terminal` is queried for `calculatedBus` in some situations.
Specifically: the voltage level has topology kind of node-breaker and all switches are opened. In this situation no bus is calculated, and the search for a `calculatedBus` fails, throwing an exception.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
A minimal example has been created as a unit test case in the branch `issue_nb_connectableBus` (module `iidm-impl`, class `NodeBreakerTest`, method `issueConnectableBus`). The following graph shows the export of the voltage level topology:

<img width="335" alt="Screen Shot 2019-10-15 at 23 02 19 " src="https://user-images.githubusercontent.com/3374819/66869517-e5750200-ef9f-11e9-9f1e-314992196ecb.png">

* **What is the expected behavior?**
A bus should be calculated in the voltage level. If no bus is calculated by design, then `null` could be a valid return value from the method `connectableBus`.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.0.0-SNAPSHOT
  - OS Version: *

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
It seems the current behavior is related to change in commit 0e2578716fc913b0d8e7f779278dc5316a201d44 where the condition for throwing the exception was changed (fixed).

**Comment by MioRtia** [comment]
Yes, this seems like the same issue as #939 ... What do you think @geofjamg @mathbagu, should `getConnectableBus()` be allowed to return `null` if there is no bus in the voltage level/the whole voltage level is disconnected?

**Comment by geofjamg** [comment]
That would lead to a mess in existing code. 
It would be simpler to return a fictitiou bus.

**Comment by zamarrenolm** [comment]
There are some points on the current code that already check for `connectableBus` returning `null`: `iidm-converter-api` `BusFilter` as an example (when the exported topology is the bus-branch).

**Comment by annetill** [comment]
Can we in a first approach retruns ````null```` and wait for the possible resulting problems ? I prefer to return a ````null```` than to introduce the notion of fictitious bus. For more, the definition of a bus is that it is connected, no ?
